### ISSUE TITLE
Add screenshot of current map on OSM

### ISSUE THREAD

**Issue by hplewis** [watmildon/SmallCityMastodonBot#8]
I really love seeing the before + after mapping comparisons, but I never remember to take the before image whenever I map anything. It'd be cool if the bot also posted a screenshot of what it looks like on OSM when it makes the post.

Biggest complexity would probably be getting the right zoom level for the screenshot, but really anything would be helpful.

**Comment by watmildon** [comment]
Love this. I'll take a look and see if I can get something knocked out. Great suggestion.

**Comment by watmildon** [comment]
I have a rudimentary setup working for this. You can see an example post here: https://en.osm.town/@SmallTownUSA/110623960529453155

I need to get it cleaned up and then will push it into the repo. In particular, I should be able to embed the image in the post and not as a link but the mastodon library I'm relying on doesn't make it obvious how to do so.

**Comment by hplewis** [comment]
Woah that's awesome. Didn't expect such a quick addition. Thanks!

**Comment by watmildon** [comment]
The pic is now embedded. Still need to do the cleanup and push to the repo. Thanks again for prodding me. I've wanted to do this for a while!

https://en.osm.town/@SmallTownUSA/110629714047915656

**Comment by watmildon** [comment]
Patched up and pushed as https://github.com/watmildon/SmallCityMastodonBot/commit/2921d42fb770321a64f43a7c238ac9c9f7cb1943
